name: quiz_app
description: Простая игра-викторина на Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/flags/
    - output/imagegen/world_map_no_labels_8k.png
    - assets/data/russia/
    - assets/data/russia/yakutia/
    - assets/data/russia/dagestan/
    - assets/data/usa/
    - assets/data/usa/oklahoma/
    - assets/data/usa/texas/
    - assets/data/china/
    - assets/data/vietnam/
    - assets/data/japan/
    - assets/data/mexico/
    - assets/data/canada/
    - assets/data/poland/
    - assets/data/france/
    - assets/data/australia/
    - assets/data/egypt/
    - assets/data/brazil/
    - assets/data/uk/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#101010"
    theme_color: "#101010"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
